<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="GSQAPC-111" name="com.carvajal.facturaclaro.test.CP_1_Emision_Factura_Retencion_Test" tests="1" failures="0" timestamp="28 nov 2018 06:59:05 GMT" time="4.123" errors="1">
  <testcase name="emisionFacturaRetencion" time="4.123" classname="com.carvajal.facturaclaro.test.CP_1_Emision_Factura_Retencion_Test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.carvajal.facturaclaro.bc.AuthorizationBC.realizarNotificacion(AuthorizationBC.java:560)
at com.carvajal.facturaclaro.bc.AuthorizationBC.notificacionEnvioConRetencion(AuthorizationBC.java:487)
at com.carvajal.facturaclaro.bc.AuthorizationBC.isOkAuthorizationPackage(AuthorizationBC.java:107)
at com.carvajal.facturaclaro.test.CP_1_Emision_Factura_Retencion_Test.emisionFacturaRetencion(CP_1_Emision_Factura_Retencion_Test.java:176)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- emisionFacturaRetencion -->
</testsuite> <!-- com.carvajal.facturaclaro.test.CP_1_Emision_Factura_Retencion_Test -->
